### ISSUE TITLE
does not do the job?

### ISSUE THREAD

**Issue by xiuliren** [seung-lab/fill_voids#6]
is this code expected to pass?

```
import fill_voids

import numpy as np

seg = np.zeros((7, 7, 7), dtype=bool)
seg[1:4, 2:5, 3:6] = True
seg[2, 3, 4] = False
fill_voids.fill(seg, in_place=True)
assert seg[2,3,4] == True
```

**Comment by william-silversmith** [comment]
Sorry I just saw this Jingpeng! It looks like the problem is that the array order is C. I call `labels = fastremap.asfortranarray(labels)` but it looks like that didn't perform an in-place transpose. I'll have to investigate more.

As a note, it does work if you do `seg = fill_voids.fill(seg, in_place=True)` but you shouldn't have to.

**Comment by william-silversmith** [comment]
I think I figured it out. The `fastremap.asfortranarray` does an in-place transposition but doesn't reset the C/F flags on the array. I'll need to fix that in fastremap. Since the array is now transposed, `assert seg[4,3,2] == True` works...

**Comment by william-silversmith** [comment]
On further consideration, the numpy documentation says that there's no way to set C/F on an existing array view. https://numpy.org/doc/stable/reference/generated/numpy.ndarray.setflags.html#numpy.ndarray.setflags it looks like you have to use the equal sign. :-/ More clumsy than I'd like. The alternative would be for me to write a fill_voids for C and F order arrays or to re-transpose C order arrays back to the way they were after going through fill_voids.

**Comment by xiuliren** [comment]
thanks for investigating this! 
I'll just use the equal sign for now.
